package AtividadeAula20201016;

public enum TipoStudio {
	J_C_STAFF,MADHOUSE,TOEI_ANIMATION,BONES,SUNRISE,PRODUCTIO_I_G,
	TMS_ENTERTAINMENT,STUDIO_DEEN,STUDIO_PIERROT,OLM,NIPPON_ANIMATION,
	A_1_PICTURES
}
